// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniFlowGW.Models;

namespace UniFlowGW.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181226122147_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("UniFlowGW.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("PasswordHash");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("UniFlowGW.Models.BindUser", b =>
                {
                    b.Property<string>("BindUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BindTime");

                    b.Property<string>("UserLogin")
                        .IsRequired();

                    b.HasKey("BindUserId");

                    b.ToTable("BindUsers");
                });

            modelBuilder.Entity("UniFlowGW.Models.ExternBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BindTime");

                    b.Property<string>("BindUserId")
                        .IsRequired();

                    b.Property<string>("ExternalId")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BindUserId");

                    b.HasIndex("Type", "ExternalId")
                        .IsUnique();

                    b.ToTable("ExternBindings");
                });

            modelBuilder.Entity("UniFlowGW.Models.PrintTask", b =>
                {
                    b.Property<int>("PrintTaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Detail");

                    b.Property<string>("Document");

                    b.Property<string>("Message");

                    b.Property<bool>("QueuedTask");

                    b.Property<int>("Status");

                    b.Property<DateTime>("Time");

                    b.Property<string>("UserID");

                    b.HasKey("PrintTaskId");

                    b.HasIndex("Time");

                    b.HasIndex("UserID");

                    b.ToTable("PrintTasks");
                });

            modelBuilder.Entity("UniFlowGW.Models.ExternBinding", b =>
                {
                    b.HasOne("UniFlowGW.Models.BindUser", "BindUser")
                        .WithMany("ExternBindings")
                        .HasForeignKey("BindUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
