//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licensing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<RSAKeyValue><Modulus>m3LXSaTvDCh3Zd5KkhRozpgjEXVy1K8xByECwQYebU+Yk4LJAqs4qEIQ0lp2bp1rZ5lbrsvr5WOSjod/1RzMKagT2CtiaqsmSgwbvBSKpMi2SYjdeZrYNnwFKdQOro+3K46KfBxliR2LcBV9kl24LfoFeeSKzI3UtB5yf80kLSE=</Modulus><Exponent>AQAB</Exponent><P>wBvJi7K4bRN2+YFa+OPENoQhBrNPVtUP+RzmxZEAKI8OA+2TAq+olu/9uOK0kwtDL/EDqcVZFzmsF+e7kjUJqw==</P><Q>zyXO9B9m5QWDhMYCnQ3isRkxnHcq+fZzFHnxgjZX5MaXBHRdfGHSk6teFd5i2WdHowSmPJbxdecNh5PrCtRQYw==</Q><DP>uUISuoU/FPEQaswzzpDXRztkHfINMM+G99THNv7+CB7shR02CAEds3D8XK9DNApIYJMr1SxbHeqf6u2uFPDQwQ==</DP><DQ>UD4aJBEB/9eZ8dXubz5QwT+8Kxsyh6/DNnxiZIl+lL2lBHG7QRJ3ywJIKPqDmina4zhK2Q+zq3N8lzdihkhmdw==</DQ><InverseQ>NDJt03PQIOcSZey+74DQIOV1mvQ5X5XIZ+RY9OzikiiBiRcaAYbX7DNu9S++vthGx40M+ClwPNiMwWB8xpdPfQ==</InverseQ><D>K7lXuQ09eAwB2ZN3IjO/byz34DdK/2vvvHOalLSl5lVXM1a8N5X1r841cRWk7mQ1C8TlNvuA9NrXJGQUntskybqBmQsm4SrBRbk9HP87BV5FaV0exhQMEoRjX2i3wCuYRwCBcxPjyrCkuu9SoLowvj2EgxqZ9lNATJtdz6VqRik=</D></RSAKeyValue>")]
        public string RsaKey {
            get {
                return ((string)(this["RsaKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\licensing.db")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DLOCR@2018")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
        }
    }
}
